"""empty message

Revision ID: 9dc57baf6583
Revises: 313db9ec745e
Create Date: 2021-05-31 23:46:32.348581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dc57baf6583'
down_revision = '313db9ec745e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('modify_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'modify_date')
    # ### end Alembic commands ###
